services:
  backend:
    build:
      context: backend
      dockerfile: ../backend.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - php_data:/var/www/html/data
    env_file:
      - backend.env
    depends_on:
      - database
    restart: always
    networks:
      - desafio

  frontend:
    build:
      context: frontend
      dockerfile: ../frontend.Dockerfile
    ports:
      - "8001:3000"
    volumes:
      - ./frontend:/app/src
      - ./frontend/public:/app/public
    env_file:
      - frontend.env
    depends_on:
      - backend
    restart: always
    networks:
      - desafio

  database:
    image: mysql:latest
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - database.env

volumes:
  db_data:
  php_data:

networks:
  desafio:
    external: true
